### ISSUE TITLE
Tip: T-Watch display and MicroPython

### ISSUE THREAD

**Issue by lyusupov** [lewisxhe/mPython_ST7789#1]
This is not a real issue report.
Below is information for those who are going to use TTGO T-Watch together with MicroPython.

The T-Watch display works reasonably good and fast with [LoBo port of MicroPython](https://github.com/loboris/MicroPython_ESP32_psRAM_LoBo) for ESP32 architecture, provided that you are using appropriate ST7789 initialization sequence, as follows:

```
import display

TFT_PIN_MISO = const(2)
TFT_PIN_MOSI = const(19)
TFT_PIN_CLK  = const(18)
TFT_PIN_SS   = const(5)
TFT_PIN_DC   = const(27)
TFT_PIN_BL   = const(12)

ST7789_INVON = const(0x21)

tft = display.TFT()
tft.init(
  tft.ST7789, backl_pin=TFT_PIN_BL, backl_on=1, miso=TFT_PIN_MISO,
  mosi=TFT_PIN_MOSI, clk=TFT_PIN_CLK, cs=TFT_PIN_SS, dc=TFT_PIN_DC,
  rot=tft.PORTRAIT_FLIP, color_bits=tft.COLOR_BITS16, splash=False,
  height=240
)
tft.tft_writecmd(ST7789_INVON)
```

[Example](https://github.com/lyusupov/SoftRF/blob/master/software/firmware/source/iLogger/main.py) of application.

![](https://user-images.githubusercontent.com/5849637/63344861-13e8af00-c35a-11e9-9ec6-5d2bffb7184d.jpg)

**Comment by lewisxhe** [comment]
I don't know that lobo contains the display driver in his micropython, thank you for your notification.

**Comment by lyusupov** [comment]
Yes, it does:
https://github.com/loboris/MicroPython_ESP32_psRAM_LoBo/wiki/display

For full list of the hardware supported, see "Content" block to the right of this Wiki page:
https://github.com/loboris/MicroPython_ESP32_psRAM_LoBo/wiki

Unfortunately, in Nov of 2018 LoBo had stopped development of uPython port onto ESP32 platform in favour of [K210](https://github.com/loboris/MicroPython_K210_LoBo) port.
But current state of his ESP32 port is still way better than the "official" one:
https://github.com/micropython/micropython
